Add req.ws to typedefs
fastify/fastify-websocket pull request #180
Opened 2022-03-02 18:42 UTC by a-a-GiTHuB-a-a

Wow, what a dumb oversight I made with my original pull request.

I use the GitHub website, so I have absolutely no idea how to run tests, but I checked and it looks okay.

2022-03-02 18:45 UTC, darkgl0w requested changes
Can you add a unit test please ?

2022-03-02 18:45 UTC, darkgl0w commented on index.d.ts
> +  interface FastifyReply {
```suggestion
  interface FastifyRequest {
```

2022-03-02 18:47 UTC, a-a-GiTHuB-a-a commented
Oops, I'm dumb.

2022-04-12 13:14 UTC, airhorns commented
Thanks for the contribution, shipped in #188

2022-04-12 13:14 UTC, closed without merging