fix: provide websocket instead of stream to avoid potential backpressure issues (#289)
fastify/fastify-websocket pull request #290
Opened 2024-03-02 20:10 UTC by mat-sz

Now `createWebSocketStream` is not called therefore there are no memory leaks/backpressure to worry about.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-03-03 09:54 UTC, mcollina requested changes
Can you please document how to get a WebSocketStream in the README?

2024-03-03 09:54 UTC, mcollina commented
I don't think having a specific function is needed, let's just document how to create it using ws.

2024-03-04 17:09 UTC, mat-sz commented
@mcollina I've added an example to README.md

2024-03-05 17:58 UTC, mcollina approved these changes
lgtm

2024-03-07 10:05 UTC, mcollina commented
CI is failing

2024-03-07 17:08 UTC, mat-sz commented
@mcollina Resolved, for some reason the unit test was relying on the count of fastify log items to be constant, updated it to fail if `level >= 50` instead.

2024-03-17 23:44 UTC, gurgunday approved these changes

2024-03-18 16:42 UTC, merged